server:
  port: ${SERVER_PORT:8081}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${ECOCIENTE_DSN:jdbc:postgresql://localhost:5432/zuppy}
    username: ${ECOCIENTE_DB_USER:postgres}
    password: ${ECOCIENTE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}